//! End-to-end checks against the public API, as an external consumer sees it.

use tpt_math_prob_markov::{
    sample_categorical, HiddenMarkovModel, Hmm, MarkovChain, MarkovError, Rng, SplitMix64,
};

/// Build a chain from raw counts, normalize it, and confirm the stationary
/// distribution, the n-step distribution and a simulation all agree.
#[test]
fn chain_workflow_from_counts_to_simulation() {
    // Observed transition counts for a two-state process.
    let mut chain = MarkovChain::new(2);
    chain.set_transition(0, 0, 900.0);
    chain.set_transition(0, 1, 100.0);
    chain.set_transition(1, 0, 500.0);
    chain.set_transition(1, 1, 500.0);
    chain.normalize();
    chain
        .validate()
        .expect("normalized counts form a stochastic matrix");

    // Analytic stationary distribution of [[0.9, 0.1], [0.5, 0.5]] is [5/6, 1/6].
    let pi = chain.stationary();
    assert!((pi[0] - 5.0 / 6.0).abs() < 1e-12, "pi = {pi:?}");
    assert!((pi[1] - 1.0 / 6.0).abs() < 1e-12, "pi = {pi:?}");

    // Deterministic n-step propagation converges to the same place.
    let propagated = chain.distribution_after(&[0.0, 1.0], 400);
    for (a, b) in pi.iter().zip(propagated.iter()) {
        assert!((a - b).abs() < 1e-9);
    }

    // So does a long simulated trajectory.
    let mut rng = SplitMix64::seed_from_u64(0xC0FFEE);
    let empirical = chain.empirical_distribution(&mut rng, 0, 200_000);
    for (a, b) in pi.iter().zip(empirical.iter()) {
        assert!(
            (a - b).abs() < 1e-2,
            "pi = {pi:?}, empirical = {empirical:?}"
        );
    }
}

/// Seeded runs are reproducible, and independent seeds are not identical.
#[test]
fn simulation_is_seed_reproducible() {
    let chain = MarkovChain::from_rows(vec![vec![0.5, 0.5], vec![0.25, 0.75]]).unwrap();
    let first = chain.run(&mut SplitMix64::seed_from_u64(1), 0, 256);
    let same = chain.run(&mut SplitMix64::seed_from_u64(1), 0, 256);
    let other = chain.run(&mut SplitMix64::seed_from_u64(2), 0, 256);

    assert_eq!(first, same);
    assert_ne!(first, other);
    assert_eq!(first.len(), 256);
    assert_eq!(first[0], 0);
}

/// A user-supplied `Rng` implementation drives the samplers just as well as
/// the one from `tpt-math-prob-core`.
#[test]
fn works_with_a_custom_rng() {
    /// Emits a fixed cycle of `u64` values.
    struct Cycle {
        values: Vec<u64>,
        index: usize,
    }

    impl Rng for Cycle {
        fn next_u64(&mut self) -> u64 {
            let v = self.values[self.index % self.values.len()];
            self.index += 1;
            v
        }
    }

    // `next_f64` uses the top 53 bits, so 0 -> 0.0 and u64::MAX -> ~1.0.
    let mut rng = Cycle {
        values: vec![0, u64::MAX],
        index: 0,
    };
    let chain = MarkovChain::from_rows(vec![vec![0.5, 0.5], vec![0.5, 0.5]]).unwrap();
    assert_eq!(chain.step(&mut rng, 0), 0);
    assert_eq!(chain.step(&mut rng, 0), 1);
    assert_eq!(sample_categorical(&mut rng, &[1.0, 1.0, 1.0]), Some(0));
}

/// Viterbi recovers a hidden sequence that was generated by the same model.
#[test]
fn hmm_round_trips_a_generated_sequence() {
    // Sticky states with strongly state-specific emissions.
    let model = HiddenMarkovModel::from_parts(
        vec![0.5, 0.5],
        vec![vec![0.98, 0.02], vec![0.02, 0.98]],
        vec![vec![0.9, 0.1], vec![0.1, 0.9]],
    )
    .expect("a well-formed model");

    let mut rng = SplitMix64::seed_from_u64(99);
    let (hidden, observed) = model.sample(&mut rng, 500);

    let decoded = model.viterbi(&observed);
    assert_eq!(decoded.len(), hidden.len());

    // Decoding is not perfect (emissions are noisy), but it should recover the
    // vast majority of the latent path, and beat the observations themselves.
    let matches = decoded
        .iter()
        .zip(hidden.iter())
        .filter(|(a, b)| a == b)
        .count();
    let raw_matches = observed
        .iter()
        .zip(hidden.iter())
        .filter(|(a, b)| a == b)
        .count();
    assert!(matches >= 470, "recovered only {matches}/500 hidden states");
    assert!(
        matches >= raw_matches,
        "smoothing should beat the raw observations"
    );

    // The decoded path is a genuinely possible explanation of the data.
    assert!(model.log_likelihood(&observed).is_finite());
}

/// Errors surface through the checked entry points instead of panicking.
#[test]
fn checked_entry_points_report_errors() {
    let mut chain = MarkovChain::new(2);
    assert_eq!(
        chain.try_set_transition(0, 9, 0.5),
        Err(MarkovError::StateOutOfRange {
            state: 9,
            states: 2
        })
    );
    assert_eq!(
        chain.try_normalize_row(0),
        Err(MarkovError::DegenerateRow { row: 0 })
    );

    let model = Hmm::uniform(2, 2);
    assert_eq!(
        model.try_viterbi(&[0, 1, 2]),
        Err(MarkovError::ObservationOutOfRange {
            observation: 2,
            observations: 2
        })
    );

    // `MarkovError` is a real `std::error::Error`, so it composes with `?`.
    fn fallible() -> Result<Vec<f64>, Box<dyn std::error::Error>> {
        Ok(MarkovChain::from_rows(vec![vec![0.25, 0.75], vec![0.6, 0.4]])?.stationary())
    }
    assert_eq!(fallible().unwrap().len(), 2);
}
