[package]
name = "tpt-math-autodiff-fwd"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "Forward-mode autodiff (dual numbers)."

[dependencies]
tpt-math-numeric = { workspace = true }

[features]
default = ["std"]
std = []
alloc = []

