[package]
name = "tpt-math-signal-fft"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "FFT (wrap rustfft)."
readme = "README.md"
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/tpt-math-signal-fft"
keywords = ["fft", "dft", "fourier", "signal-processing", "spectral"]
categories = ["mathematics", "science", "algorithms"]

[dependencies]
rustfft = "6.4.1"
tpt-math-numeric = { workspace = true, features = ["std"] }

[features]
default = []


[lints]
workspace = true

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "signal_fft_bench"
harness = false
