[package]
name = "tpt-math-prob-sampler"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "Sampling strategies."
readme = "README.md"
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/tpt-math-prob-sampler"
keywords = ["sampling", "random", "rng", "distribution", "strategies"]
categories = ["mathematics", "science", "algorithms"]

[dependencies]
tpt-math-prob-core = { workspace = true, default-features = false }

[features]
default = ["std"]
std = ["tpt-math-prob-core/std"]
alloc = ["tpt-math-prob-core/alloc"]


[lints]
workspace = true
