[package]
name = "tpt-math-signal-filter"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "FIR/IIR filters, windowing."
readme = "README.md"
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/tpt-math-signal-filter"
keywords = ["filters", "fir", "iir", "windowing", "signal-processing"]
categories = ["mathematics", "science", "algorithms"]

[dependencies]
tpt-math-numeric = { workspace = true }
tpt-math-signal-fft = { workspace = true }

[features]
default = []

