[package]
name = "tpt-math-autodiff"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "Umbrella: re-exports fwd+rev."
readme = "README.md"
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/tpt-math-autodiff"
keywords = ["autodiff", "gradients", "umbrella", "differentiation", "reverse-mode"]
categories = ["mathematics", "science", "algorithms"]

[dependencies]
tpt-math-autodiff-fwd = { workspace = true, optional = true }
tpt-math-autodiff-rev = { workspace = true, optional = true }

[features]
default = ["tpt-math-autodiff-fwd", "tpt-math-autodiff-rev"]
tpt-math-autodiff-fwd = ["dep:tpt-math-autodiff-fwd"]
tpt-math-autodiff-rev = ["dep:tpt-math-autodiff-rev"]


[lints]
workspace = true
